@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(Новый_клиент, "Новый клиент", "")
System(Сайт, "Сайт", "Сайт банка «Стандарт»")
System(АБС, "АБС", "Автоматизированная банковская система (АБС)")
System(Система_колцентра, "Система кол-центра", "Система кол-центра банка «Стандарт»")
Person(Менеджер_колцентра, "Менеджер кол-центра", "")
Person(Клиент, "Клиент", "")
System(Интернет_банк, "Интернет-банк", "Интернет-банк банка «Стандарт»")
System(СМС_шлюз, "СМС-шлюз телеком-оператора", "")
Person(Менеджер_бэкофиса, "Менеджер бэк-офиса", "")

Rel(Новый_клиент, Сайт, "Получает данные о депозите / создает заявки на депозит", "")
Rel(Сайт, АБС, "Получает данные о депозитах с актуальными ставками", "")
Rel(Сайт, Система_колцентра, "Отправляет заявки на депозит", "")
Rel(Менеджер_колцентра, Система_колцентра, "Просматривает заявки на депозит / подтверждает условия депозита", "")
Rel(Клиент, Интернет_банк, "Получает список доступных депозитов с актуальными ставками и персонализированными ставками лично для себя / создает заявки на депозит с указанием счета и суммы", "")
Rel(Интернет_банк, АБС, "Получает список доступных депозитов с актуальными ставками и персонализированными ставками лично для клиента / отправляет заявки на депозит с указанием счета и суммы", "")
Rel(АБС, СМС_шлюз, "Отправляет СМС с кодом подтверждения / отправляет СМС-уведомления", "")
Rel(СМС_шлюз, Клиент, "Отправляет СМС с кодом подтверждения / отправляет СМС-уведомления", "")
Rel(Менеджер_бэкофиса, АБС, "Получает заявки на депозит / подтверждает условия депозита", "")
Rel(Система_колцентра, АБС, "Получает список заявок на депозит / отправляет заявки на депозит / подтверждает условия депозита", "")
@enduml