@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(Интернет_банк_boundary, "Интернет-банк") {
    Container(Веб_интерфейс, "Веб-интерфейс", "HTML, CSS, JavaScript", "Веб-интерфейс клиент-серверной системы интернет-банка")
    Container(Приложение_интернет_банка, "Приложение интернет-банка", "ASP.NET MVC 4.5, .NET Framework 4.5", "Серверная часть клиент-серверной системы интернет-банка")
    ContainerDb(База_данных_интернет_банка, "База данных интернет-банка", "MS SQL", "")
    Container(Сервис_депозитов, "Сервис депозитов", "C#, ASP.NET Core", "")
}

System_Boundary(АБС_boundary, "АБС") {
    Container(Десктопное_приложение, "Десктопное приложение", "Delphi", "Десктопный клиент автоматизированной банковской системы (АБС)")
    ContainerDb(База_данных_АБС, "База данных АБС", "Oracle", "")
}

System(СМС_шлюз_boundary, "СМС-шлюз телеком-оператора", "")
Person(Клиент_boundary, "Клиент", "")
Person(Менеджер_бэкофиса_boundary, "Менеджер бэк-офиса", "")

Rel(Клиент_boundary, Веб_интерфейс, "HTTPS", "")
Rel(Веб_интерфейс, Приложение_интернет_банка, "HTTPS", "")
Rel(Приложение_интернет_банка, База_данных_интернет_банка, "SQL/TCP", "Чтение-запись данных о заявках и депозитах")
Rel(Приложение_интернет_банка, Сервис_депозитов, "HTTPS", "Получает список доступных депозитов с актуальными ставками и персонализированными ставками лично для клиента")
Rel(Сервис_депозитов, База_данных_интернет_банка, "SQL/TCP", "Чтение-запись данных о депозитах")
Rel(Сервис_депозитов, База_данных_АБС, "PL-SQL/TCP", "Получает список доступных депозитов с актуальными ставками и персонализированными ставками лично для клиента")
Rel(Приложение_интернет_банка, База_данных_АБС, "PL-SQL/TCP", "Отправляет заявки на депозит с указанием счета и суммы")
Rel(Менеджер_бэкофиса_boundary, Десктопное_приложение, "", "Получает заявки на депозит / подтверждает условия депозита")
Rel(Десктопное_приложение, База_данных_АБС, "PL-SQL/TCP", "Чтение-запись данных о заявках и депозитах")
Rel(Десктопное_приложение, СМС_шлюз_boundary, "SMPP", "Отправляет СМС с кодом подтверждения / отправляет СМС-уведомления")
Rel(СМС_шлюз_boundary, Клиент_boundary, "HTTPS", "Отправляет СМС с кодом подтверждения / отправляет СМС-уведомления")

@enduml