@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(Система_колцентра_boundary, "Система кол-центра банка «Стандарт»") {
    Container(Веб_интерфейс, "Веб-интерфейс", "React.js", "Веб-интерфейс клиент-серверной системы партнерского кол-центра")
    Container(Платформа_системы, "Платформа системы кол-центра", "Java, Spring Boot", "Серверная часть клиент-серверной системы кол-центра банка «Стандарт»")
    Container(Сервис_текущих_ставок, "Сервис текущих ставок", "Java, Spring Boot", "")
    ContainerDb(База_данных_платформы, "База данных платформы", "PostgreSQL", "")
    ContainerDb(База_данных_сервиса, "База данных сервиса", "PostgreSQL", "")
}

System_Boundary(АБС_boundary, "АБС") {
    Container(Десктопное_приложение, "Десктопное приложение", "Delphi", "Десктопный клиент автоматизированной банковской системы (АБС)")
    ContainerDb(База_данных_АБС, "База данных АБС", "Oracle", "")
}

System(Система_партнерского_колцентра_boundary, "Система партнерского кол-центра", "")
Person(Клиент_boundary, "Клиент", "")
Person(Менеджер_колцентра_boundary, "Менеджер кол-центра", "")
Person(Менеджер_партнерского_колцентра_boundary, "Менеджер партнерского кол-центра", "")

Rel(Клиент_boundary, Веб_интерфейс, "HTTPS", "Звонит и получает данные о текущих ставках банка")
Rel(Веб_интерфейс, Платформа_системы, "HTTPS", "")
Rel(Платформа_системы, База_данных_платформы, "SQL/TCP", "Чтение-запись данных о звонках")
Rel(Веб_интерфейс, Сервис_текущих_ставок, "HTTPS", "Получает данные о текущих ставках банка")
Rel(Сервис_текущих_ставок, База_данных_сервиса, "SQL/TCP", "Чтение-запись данных о текущих ставках")
Rel(Сервис_текущих_ставок, Десктопное_приложение, "HTTPS", "Получает данные о текущих ставках банка")
Rel(Сервис_текущих_ставок, Система_партнерского_колцентра_boundary, "SFTP", "Отправляет файл с текущими ставками по депозитам")
Rel(Менеджер_колцентра_boundary, Веб_интерфейс, "", "Принимает звонки клиентов / получает данные о текущих ставках банка")
Rel(Менеджер_партнерского_колцентра_boundary, Система_партнерского_колцентра_boundary, "", "Принимает звонки клиентов / получает данные о текущих ставках банка из файла")
Rel(Десктопное_приложение, База_данных_АБС, "PL-SQL/TCP", "Чтение-запись данных о заявках и депозитах")

@enduml