@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(Клиент, "Клиент", "")
System(Система_партнерского_колцентра, "Система партнерского кол-центра", "")
System(Система_колцентра, "Система кол-центра", "Система кол-центра банка «Стандарт»")
System(АБС, "АБС", "Автоматизированная банковская система (АБС)")
Person(Менеджер_колцентра, "Менеджер кол-центра", "")
Person(Менеджер_партнерского_колцентра, "Менеджер партнерского кол-центра", "")

Rel(Клиент, Система_партнерского_колцентра, "Звонит и получает данные о текущих ставках банка", "")
Rel(Клиент, Система_колцентра, "Звонит и получает данные о текущих ставках банка", "")
Rel(Менеджер_колцентра, Система_колцентра, "Принимает звонки клиентов / получает данные о текущих ставках банка", "")
Rel(Система_колцентра, АБС, "Получает данные о текущих ставках банка", "")
Rel(Менеджер_партнерского_колцентра, Система_партнерского_колцентра, "Принимает звонки клиентов / получает данные о текущих ставках банка из файла с текущими ставками по депозитам, полученный по SFTP-протоколу", "")
Rel(Система_колцентра, Система_партнерского_колцентра, "Отправляет файл с текущими ставками по депозитам по SFTP-протоколу", "")
@enduml